#Someday we should approach this in a more proffesional way
#Changing the whole structure and writting a decent makefile

#CURRENTLY we should invoke this with sh 


gcc Main.c Read.c Intracellular.c PDESolver.c Utilities.c Roberto.c HybridHandling.c -o EXE -O2
#append -lm if compiling on linux